# Generated by Django 2.1.1 on 2018-10-31 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_score',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='popularity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
